spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/testonly?serverTimezone=Asia/Seoul
#    username: testuser
#    password: 1234

  mail:
    host: smtp.naver.com
    port: 465
    username: kangjiiii02@naver.com
    password: vV2386889##
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com

  redis:
    host: 127.0.0.1
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update # create update create-update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: mysql
    open-in-view: true
  profiles:
    include: oauth, security, database, redis

logging:
  level:
    org.springframework.web.client: debug
    org.hibernate.sql: debug
    org.hibernate.type: trace
    org.springframework.security: debug

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

