spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: mysql
    open-in-view: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    url: >-
      jdbc:mysql://database-real.cu1hvqihmdeb.ap-northeast-2.rds.amazonaws.com:3306/devillage?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: db-username
    password: db-password
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: my-redis-ro.51trim.ng.0001.apn2.cache.amazonaws.com
    port: '6379'
  mail:
    host: smtp.naver.com
    port: '465'
    username: mail-username
    password: mail-password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 058a14d6662214899e57
            client-secret: github-secret
            scope:
              - 'read:user'
              - 'user:email'
          google:
            client-id: 586149447203-mpro8b55ov8o7i3pct1nulb15j6igi8o.apps.googleusercontent.com
            client-secret:
            scope:
              - email
              - profile
logging:
  level:
    org.springframework.web.client: debug
    org.hibernate.sql: debug
    org.hibernate.type: trace
    org.springframework.security: debug
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
cloud:
  aws:
    credentials:
      accessKey: aws-accessKey
      secretKey: aws-secretKey
    s3:
      bucket: devillage-image
      dir: image
    region:
      static: ap-northeast-2
    stack:
      auto: false
jwt:
  secretKey: jwt-secretKey
  refreshKey: jwt-refreshKey
